<?php $this->useLayout('admin:layout') ?>
<?php $this->startBlock('content') ?>

<aside class="admin-nav-bar"><ul class="admin-nav"></ul></aside>
<div class="admin-inner-content">

    <!-- TODO: plugins should add their pages here (with server side) -->

    <div class="admin-page admin-page-dashboard">
        <h1>Dashboard</h1>
        <div class="row">
            <div class="col col-50">
                <input type="text" value="Testing">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
            </div>
            <div class="col col-50">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-posts">
        <h1>Posts</h1>
        <div class="row">
            <div class="col col-33 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
            </div>
            <div class="col col-33 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-33 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-menus">
        <h1>Menus</h1>
        <div class="row">
            <div class="col col-66 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
            </div>
            <div class="col col-33 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-categories">
        <h1>Categories</h1>
        <div class="row">
            <div class="col col-25 col-md-50 col-sm-50">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
            </div>
            <div class="col col-25 col-md-50 col-sm-50">
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
            </div>
            <div class="col col-25 col-md-50 col-sm-50">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-25 col-md-50 col-sm-50">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-tags">
        <h1>Tags</h1>
        <div class="row">
            <div class="col col-50 col-md-100 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
            </div>
            <div class="col col-25 col-md-50 col-sm-50">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-25 col-md-50 col-sm-50">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-media">
        <h1>Media</h1>
        <div class="row">
            <div class="col col-25 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
            </div>
            <div class="col col-50 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-25 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-settings">
        <h1>Settings</h1>
        <div class="row">
            <div class="col col-20 col-md-100 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
            </div>
            <div class="col col-60 col-md-100 col-sm-100">
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-20 col-md-100 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-user-list">
        <h1>Users</h1>
        <div class="row">
            <div class="col col-25 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-75 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-user-groups">
        <h1>Groups</h1>
        <div class="row">
            <div class="col col-75 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-25 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>

    <div class="admin-page admin-page-permissions">
        <h1>Permissions</h1>
        <div class="row">
            <div class="col col-20 col-md-100 col-sm-100">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis malesuada risus at sodales. Suspendisse in tincidunt magna. Nullam pulvinar nibh non fermentum eleifend. Nulla ornare nulla sit amet dui venenatis tempor. Integer dictum sapien diam, eget venenatis felis semper nec. Duis dapibus nunc pellentesque tellus pretium, vel aliquet sapien pulvinar. Ut id ipsum id neque tempor egestas. Aliquam erat volutpat. Integer nec rhoncus tellus, non bibendum sem. Curabitur ut finibus metus. Sed ex lectus, semper a libero vel, lobortis luctus dui. Aliquam leo ante, dapibus sed dignissim eget, convallis eget risus.
            </div>
            <div class="col col-60 col-md-100 col-sm-100">
                Suspendisse potenti. Aenean sed urna massa. Integer dictum, elit sit amet mattis sodales, libero leo suscipit augue, ut tempor libero elit eu velit. Phasellus sit amet sagittis tortor. Aliquam pharetra in ante vitae malesuada. Nam vulputate gravida commodo. Aliquam erat volutpat. Aliquam lacinia sagittis lacus vitae faucibus.
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
            <div class="col col-20 col-md-100 col-sm-100">
                Sed consectetur urna commodo enim lacinia auctor. Aenean sollicitudin euismod risus, eget euismod turpis auctor a. Nunc fringilla ultricies ipsum. Duis mi justo, sodales vitae turpis quis, cursus scelerisque odio. Nam eget placerat enim, quis pellentesque ante. Nullam sollicitudin libero velit, vulputate tempor odio auctor nec. Nullam tempus risus odio, id viverra enim volutpat id. Nullam tincidunt est ut ipsum pharetra, bibendum ullamcorper dui tristique. In eu dui rutrum, fermentum tellus ac, lacinia elit. Donec non bibendum odio, euismod luctus velit.
            </div>
        </div>
    </div>



</div>

<?php $this->endBlock('content') ?>
<?php $this->addScript('/admin/static/jquery.admin-app.js', ['type' => 'module', 'defer' => null]) ?>
<?php $this->startBlock('scripts') ?>
<script>

$(document).ready(function() {

  const adminApp = $('main').adminApp();

  const pages = {
    'dashboard': new Page(adminApp),
    'posts': new Page(adminApp),
    'media': new Page(adminApp),
    'categories': new Page(adminApp),
    'tags': new Page(adminApp),
    'menus': new Page(adminApp),
    'users': new Page(adminApp),
    'groups': new Page(adminApp),
    'permissions': new Page(adminApp),
    'settings': new Page(adminApp)
  };

  const routes = {
      '/': function () { adminApp.showPage('dashboard') },
      '/posts': function () { adminApp.showPage('posts') },
      '/media': function () { adminApp.showPage('media') },
      '/categories': function () { adminApp.showPage('categories') },
      '/tags': function () { adminApp.showPage('tags') },
      '/menus': function () { adminApp.showPage('menus') },
      '/users': function () { adminApp.showPage('users') },
      '/groups': function () { adminApp.showPage('groups') },
      '/permissions': function () { adminApp.showPage('permissions') },
      '/settings': function () { adminApp.showPage('settings') },
  };

  const menuItems = [
      {id: 'dashboard', label: 'Dashboard', icon: 'fa-solid fa-house', route: '/'}, // TODO: label i18n
      {id: 'posts', label: 'Posts', icon: 'fas fa-file', route: '/posts'},
      {id: 'media', label: 'Media', icon: 'fa-solid fa-photo-film', route: '/media'},
      {id: 'categories', label: 'Categories', icon: 'fa-solid fa-sitemap', route: '/categories'},
      {id: 'tags', label: 'Tags', icon: 'fa-solid fa-hashtag', route: '/tags'},
      {id: 'menus', label: 'Menus', icon: 'fa-solid fa-bars', route: '/menus'},
      {id: 'users', label: 'Users', icon: 'fa-solid fa-users', children: [
          {id: 'user_list', label: 'List', route: '/users'},
          {id: 'user_groups', label: 'Groups', route: '/groups'},
          {id: 'user_permissions', label: 'Permissions', route: '/permissions'}
      ]},
      {id: 'settings', label: 'Settings', icon: 'fa-solid fa-gear', route: '/settings'}
  ];

  // TODO: plugins should init here

  adminApp.init({
      pages: pages,
      routes: routes,
      menuItems: menuItems
  });

});

</script>
<?php $this->endBlock('scripts') ?>
